site_name: Open SDG

repo_url: https://github.com/open-sdg/open-sdg
site_description: 'Open SDG - A platform for collecting and disseminating data for the Sustainable Development Goal global indicators.'
theme:
    name: readthedocs
    custom_dir: docs-theme/

markdown_extensions:
    - toc:
        permalink: True

extra_css:
    - css/architecture.css
    - css/home.css

nav:
    - Home: index.md
    - Open SDG features: open-sdg-features.md
    - Potential users: potential-users.md
    - Frequently Asked Questions: faq.md
    - Community:
        - Platform updates: updates.md
        - Change log: changelog.md
        - Getting Support: support.md
        - Contribution guidelines: contribution.md
        - Code of conduct: conduct.md
    - Glossary of terms: glossary.md
    - Architecture diagram: architecture.md
    - Requirements: requirements.md
    - Quick start:
        - Installation: quick-start.md
        - "Tutorial: Changing the logo and favicon": tutorials/change-logo.md
        - "Tutorial: Frontpage text configuration": tutorials/frontpage-config.md
        - "Tutorial: Adding indicators": tutorials/add-indicator.md
        - "Tutorial: Adding languages": tutorials/add-language.md
        - "Tutorial: Changing colors": tutorials/change-colors.md
        - "Tutorial: Changing the site-wide banner": tutorials/change-banner.md
        - "Tutorial: Contibuting to SDG Translations": tutorials/contribute-translations.md
        - "Tutorial: Creating pages": tutorials/create-pages.md
    - Data provider guidance:
        - Data format: data-format.md
        - Data sources: data-sources.md
        - Data schema: data-schema.md
        - Making updates: making-updates.md
        - Metadata format: metadata-format.md
        - Metadata file formats: metadata-file-formats.md
        - Chart types: charts.md
    - Developer guidance:
        - Local development: development.md
        - Cookies and privacy: cookies.md
        - Deployment: deployment.md
        - Site configuration: configuration.md
        - Data configuration: data-configuration.md
        - Indicator configuration: indicator-configuration.md
        - Customisation: customisation.md
        - Jekyll and Open SDG: jekyll-and-open-sdg.md
        - Jekyll templates: jekyll-templates.md
        - Translation: translation.md
        - Maps: maps.md
        - Analytics: analytics.md
        - Reporting status: reporting-status.md
        - Troubleshooting: troubleshooting.md
    - Automation:
        - GitHub Actions: automation/github-actions.md
        - CircleCI: automation/circle-ci.md
        - TravisCI: automation/travis-ci.md
        - Jenkins: automation/jenkins.md
        - Github integration: automation/github.md
        - Triggered site builds: automation/triggered-site-builds.md
    - Hosting:
        - Github pages: hosting/github-pages.md
        - AWS S3: hosting/aws-s3.md
        - Linux server: hosting/linux-server.md
        - Production environments: hosting/production.md
        - Github pages (production): hosting/github-pages-production.md
    - Upgrades:
        - Upgrade process: upgrades/upgrade-process.md
        - Upgrading to 2.1.0: upgrades/upgrading-2-1-0.md
        - Upgrading to 2.0.0: upgrades/upgrading-2-0-0.md
        - Upgrading to 1.8.0: upgrades/upgrading-1-8-0.md
        - Upgrading to 1.7.0: upgrades/upgrading-1-7-0.md
        - Upgrading to 1.6.0: upgrades/upgrading-1-6-0.md
        - Upgrading to 1.5.0: upgrades/upgrading-1-5-0.md
        - Upgrading to 1.4.0: upgrades/upgrading-1-4-0.md
        - Upgrading to 1.3.0: upgrades/upgrading-1-3-0.md
        - Upgrading to 1.2.0: upgrades/upgrading-1-2-0.md
        - Upgrading to 1.0.0: upgrades/upgrading-1-0-0.md
        
        
