site_name: Open SDG

repo_url: https://github.com/open-sdg/open-sdg
site_description: 'Open SDG - A platform for collecting and disseminating data for the Sustainable Development Goal global indicators.'
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: True

extra_css:
    - css/architecture.css
    - css/home.css

pages:
    - Home: index.md
    - About: about.md
    - News & events: news-and-events.md
    - Open SDG features: open-sdg-features.md
    - Potential users: potential-users.md
    - Frequently Asked Questions: faq.md
    - Open SDG users:
        - List of users: community.md
        - "Case study: Armenia": case-studies/armenia.md
        - "Case study: City of Los Angeles": case-studies/cityoflosangeles.md
        - "Case study: Germany": case-studies/germany.md
        - "Case study: Kyrgyzstan": case-studies/kyrgyzstan.md
        - "Case study: Rwanda": case-studies/rwanda.md
        - "Case study: United Kingdom": case-studies/uk.md
    - Community:
        - Platform updates: updates.md
        - Support: support.md
        - Contribution guidelines: contribution.md
        - Code of conduct: conduct.md
    - Change log: changelog.md
    - Glossary of terms: glossary.md
    - Architecture diagram: architecture.md
    - Requirements: requirements.md
    - Quick start:
        - Installation: quick-start.md
        - "Tutorial: Changing the logo and favicon": tutorials/change-logo.md
        - "Tutorial: Frontpage configuration": tutorials/frontpage-config.md
        - "Tutorial: Adding indicators": tutorials/add-indicator.md
        - "Tutorial: Adding languages": tutorials/add-language.md
        - "Tutorial: Changing colors": tutorials/change-colors.md
        - "Tutorial: Changing the site-wide banner": tutorials/change-banner.md
    - Data providers:
        - Making updates: making-updates.md
        - Metadata format: metadata-format.md
        - Metadata file formats: metadata-file-formats.md
        - Data format: data-format.md
        - Data sources: data-sources.md
        - Chart types: charts.md
    - Developers:
        - Local development: development.md
        - Deployment: deployment.md
        - Site configuration: configuration.md
        - Data configuration: data-configuration.md
        - Customisation: customisation.md
        - Jekyll templates: jekyll-templates.md
        - Jekyll and Open SDG: jekyll-and-open-sdg.md
        - Translation: translation.md
        - Maps: maps.md
        - Analytics: analytics.md
        - Reporting status: reporting-status.md
        - Social media sharing: social-media-sharing.md
        - Troubleshooting: troubleshooting.md
    - Automation:
        - GitHub Actions: automation/github-actions.md
        - CircleCI: automation/circle-ci.md
        - TravisCI: automation/travis-ci.md
        - Jenkins: automation/jenkins.md
        - Github integration: automation/github.md
        - Triggered site builds: automation/triggered-site-builds.md
    - Hosting:
        - Github pages: hosting/github-pages.md
        - AWS S3: hosting/aws-s3.md
        - Linux server: hosting/linux-server.md
        - Production environments: hosting/production.md
        - Github pages (production): hosting/github-pages-production.md
    - Upgrades:
        - Upgrade process: upgrades/upgrade-process.md
        - Upgrading to 1.0.0: upgrades/upgrading-1-0-0.md
        - Upgrading to 1.2.0: upgrades/upgrading-1-2-0.md
        - Upgrading to 1.3.0: upgrades/upgrading-1-3-0.md
