site_name: Open SDG

repo_url: https://github.com/open-sdg/open-sdg
site_description: 'Open SDG - A platform for collecting and disseminating data for the Sustainable Development Goal global indicators.'
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: True

extra_css:
    - css/architecture.css
    - css/home.css

pages:
    - Home: index.md
    - About: about.md
    - Open SDG features: open-sdg-features.md
    - Frequently Asked Questions: faq.md
    - Community:
        - Change log: changelog.md
        - Who is using: community.md
        - Case studies:
            - Armenia: case-studies/armenia.md
            - City of Los Angeles: case-studies/cityoflosangeles.md
            - Germany: case-studies/germany.md
            - Kyrgyzstan: case-studies/kyrgyzstan.md
            - Rwanda: case-studies/rwanda.md
        - Support: support.md
        - Contribution guidelines: contribution.md
        - Code of conduct: conduct.md
    - Glossary of terms: glossary.md
    - Architecture diagram: architecture.md
    - Requirements: requirements.md
    - Quick start: quick-start.md
    - Data providers:
        - Making updates: making-updates.md
        - Metadata format: metadata-format.md
        - Data format: data-format.md
        - Data sources: data-sources.md
    - Developers:
        - Local development: development.md
        - Deployment: deployment.md
        - Configuration: configuration.md
        - Customisation: customisation.md
        - Translation: translation.md
        - Maps: maps.md
        - Analytics: analytics.md
        - Reporting status: reporting-status.md
    - Automation:
        - GitHub Actions: automation/github-actions.md
        - CircleCI: automation/circle-ci.md
        - TravisCI: automation/travis-ci.md
        - Jenkins: automation/jenkins.md
        - Github integration: automation/github.md
    - Hosting:
        - Github pages: hosting/github-pages.md
        - AWS S3: hosting/aws-s3.md
        - Linux server: hosting/linux-server.md
